stages:
  - test

variables:
  DOCKER_IMAGE: python:3.9  # Choose the Python version you want to use

before_script:
  - apt-get update -qy
  - apt-get install -y python3-pip
  - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - python consolidated.py  # Replace 'your_script.py' with the actual filename of your Python script
